"use client";
import { ThemeContext } from "./ThemeContex";
import { Navbar } from "@/components/Navbar/Navbar";
import { Brand } from "@/components/shared/Brand/Brand";
import { Footer } from "@/components/Footer/Footer";
import styles from "./layout.module.css";

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <head>
                <title>Piotr Kulcenty - Violin Maker based in London</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
            </head>
            <ThemeContext.Provider value='dark'>
                <body>
                    <header>
                        <Navbar />
                    </header>
                    <main className={styles.layout}>
                        <Brand />
                        {children}
                    </main>
                    <footer>
                        <Footer />
                    </footer>
                </body>
            </ThemeContext.Provider>
        </html>
    );
}
